name: Comment Bot
on:
    issue_comment:
        types: [created, edited] #triggers whenever someone posts a comment on an issue or pull request
permissions:
    issues: write
    pull-requests: write
jobs:
    reply:
        runs-on: ubuntu-latest
        steps:
            - name: Reply with a comment
              uses: peter-evans/create-or-update-comment@v3
              with:
                issue-number: ${{ github.event.issue.number }}
                edit-mode: replace
                body: |
                  you said: ${{ github.event.comment.body }}
                  <!-- bot-comment-id: response -->
